FROM node:20-alpine

WORKDIR /app

RUN npm install -g expo-cli @expo/ngrok

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 8081
EXPOSE 19000
EXPOSE 19001
EXPOSE 19002

CMD ["npx", "expo", "start", "--host", "lan"]
